export const colors = {
  background: 'var(--background)',
  surface: 'var(--surface)',
  surfaceSolid: 'var(--surface-solid)',
  border: 'var(--border)',
  borderStrong: 'var(--border-strong)',
  text: 'var(--text)',
  textSecondary: 'var(--text-secondary)',
  textMuted: 'var(--text-muted)',
  glass: 'var(--glass)',
  glassHover: 'var(--glass-hover)',
  shadow: 'var(--shadow)',
  shadowLight: 'var(--shadow-light)',
  success: 'var(--success)',
  error: 'var(--error)',
  errorMuted: 'var(--error-muted)',
  errorSurface: 'var(--error-surface)',
  errorBorder: 'var(--error-border)',
  warning: 'var(--warning)',
  transparent: 'var(--transparent)',
};
